Chapter 6 and Chapter 7 done.
brumaire-agency/aptos-shores-courses pull request #7
Opened 2024-01-19 17:59 UTC by snehasharma76

2024-01-22 17:59 UTC, 0xNekr requested changes

2024-01-23 05:45 UTC, snehasharma76 commented on sources/quest_3/chapter_6/step_22/step_22.md
> +It is time for you to stop thinking about if you should learn MOVE or not and get into experiemnting with the `if-else` in the code here. Create a function `build_house` with parameter `data` that wi
done

2024-01-23 05:48 UTC, snehasharma76 commented on sources/quest_3/chapter_6/step_21/step_21_start.move
> +    // declare a constant named `Min_tress` of type `u8` and assign a value 20 to it.
yes we decided on going with the flow of code and then rearranging so that is why.

2024-01-23 05:50 UTC, snehasharma76 commented on sources/quest_3/chapter_6/step_23/step_23.md
Ahh yes I have a few steps in mind will try to sneak that in here.

2024-01-23 05:51 UTC, snehasharma76 commented on sources/quest_3/chapter_6/step_22/step_22.md
> +if(<condition>)
ahh actually since we are talking about a statement and not the body we can omit the curly brackets there since it is a single line.

2024-01-30 09:41 UTC, 0xNekr approved these changes

2024-01-30 09:41 UTC, merged